coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    # rules for the entire project
    project:
      default:
        target: 80

    # rules for the PR/commit
    patch:
      default:
        target: 90

    # changes not included in PR/commit
    changes: no
