language: python
python:
  - "3.5"
  - "3.6"

# restrict to branches
branches:
  only:
    - master
    - develop

# command to install system dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg mediainfo

# commands to install python dependencies
install:
  # the features used in setup.cfg require at decent version of setuptools
  - python -m pip install --upgrade "setuptools>=40.0"

  # install dependencies for test
  - python -m pip install -e ".[tests]"

# commands to run tests
script:
  # run tests
  - python -m coverage run setup.py test

  # run code formatting tests
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then python -m black . --check; fi
  - python -m flake8

# commands to manage tests results
after_script:
  # show coverage stats
  - python -m coverage report -m

  # upload coverage stats to codecov.io
  # codecov token is stored in travis settings
  - python -m codecov -X gcov