name: Tests

on: [push]

jobs:
  check:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: install native dependencies (Ubuntu)
        run: sudo apt-get update && sudo apt-get install -y ffmpeg mediainfo
        if: matrix.os == 'ubuntu-latest'

      - name: install native dependencies (MacOS)
        run: brew install ffmpeg mediainfo
        if: matrix.os == 'macos-latest'

      - name: install native dependencies (Windows)
        run: choco install ffmpeg mediainfo-cli
        if: matrix.os == 'windows-latest'

      - name: print ffprobe and mediainfo versions
        run: ffprobe -version && mediainfo --version

      - name: install python tests dependencies
        run: pip install -e '.[tests]'

      - name: run tests
        run: python -m pytest -v --cov src

      - name: run isort
        run: python -m isort . --check

      - name: run black
        run: python -m black . --check

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

